# Generated by Django 2.2.3 on 2019-07-24 17:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('primary_part', models.CharField(choices=[('pecs', 'pecs'), ('quadriceps', 'quadriceps'), ('glute', 'glute'), ('biceps', 'biceps'), ('triceps', 'triceps'), ('deltoids', 'deltoids'), ('lats', 'lats'), ('traps', 'traps'), ('hamstrings', 'hamstrings'), ('abs', 'abs')], max_length=100, verbose_name='primary part of body')),
                ('secondary_part', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('repeated_no', models.IntegerField(default=0)),
                ('max_repeat_no', models.IntegerField(default=2)),
                ('progress_choice', models.CharField(blank=True, choices=[('weights', 'weights'), ('reps', 'reps'), ('sets', 'sets')], max_length=100, null=True, verbose_name='what to do for the next set')),
                ('sets_no', models.IntegerField()),
                ('reps_no', models.IntegerField()),
                ('break_time_length', models.TimeField()),
                ('weights', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('repeated_no', models.IntegerField(default=0)),
                ('max_repeat_no', models.IntegerField(default=2)),
                ('progress_choice', models.CharField(blank=True, choices=[('weights', 'weights'), ('reps', 'reps'), ('sets', 'sets')], max_length=100, null=True, verbose_name='what to do for the next set')),
                ('sets_no', models.IntegerField()),
                ('reps_no', models.IntegerField()),
                ('break_time_length', models.TimeField()),
                ('workout_sets', models.ManyToManyField(to='wtapp.WorkoutSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('repeated_no', models.IntegerField(default=0)),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('super_sets', models.ManyToManyField(to='wtapp.SuperSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('worktout_sets', models.ManyToManyField(to='wtapp.WorkoutSet')),
            ],
        ),
        migrations.CreateModel(
            name='LogExcercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.FloatField()),
                ('sets_no', models.IntegerField()),
                ('reps_no', models.IntegerField()),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtapp.Excercise')),
            ],
        ),
    ]
