# Generated by Django 2.2.3 on 2019-07-25 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superset',
            name='break_time_length',
            field=models.TimeField(default=datetime.time(0, 1, 30)),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='break_time_length',
            field=models.TimeField(default=datetime.time(0, 1, 30)),
        ),
    ]
